import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavigationBar from './layoutComponents';

export const metadata: Metadata = {
  title: 'Frege'
  // description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavigationBar>{children} </NavigationBar>
      </body>
    </html>
  );
}
