auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  max_query_parallelism: 32
  max_entries_limit_per_query: 50000

frontend:
  max_outstanding_per_tenant: 4096

querier:
  max_concurrent: 32

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
