version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"   # the requirements.txt file location
    schedule:
      interval: "weekly"

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"  