from fregepoc.analyzers.core.cpp import *
from fregepoc.analyzers.core.java import *
from fregepoc.analyzers.core.kotlin import *
from fregepoc.analyzers.core.php import *
from fregepoc.analyzers.core.python import *
from fregepoc.analyzers.core.ruby import *
from fregepoc.analyzers.core.rust import *
from fregepoc.analyzers.core.golang import *
from fregepoc.analyzers.core.swift import *
