global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'frege-prometheus:9090' ]
  - job_name: flower
    static_configs:
      - targets: ['frege-flower:5555']
