# Generated by Django 4.0.3 on 2022-04-08 19:35

import datetime

from django.db import migrations, models

import frege.indexers.models


class Migration(migrations.Migration):

    dependencies = [
        ("indexers", "0003_alter_githubindexer_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceforgeIndexer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_page",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The last visited page.",
                        verbose_name="current page",
                    ),
                ),
                (
                    "rate_limit_timeout",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        verbose_name="rate limit timeout",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(frege.indexers.models.BaseIndexer,),
        ),
        migrations.AlterModelOptions(
            name="sourceforgeindexer",
            options={
                "verbose_name": "Sourceforge Indexer",
                "verbose_name_plural": "Sourceforge Indexer",
            },
        ),
    ]
