# Generated by Django 4.0.4 on 2022-05-10 19:23

import datetime

from django.db import migrations, models
from datetime import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("indexers", "0004_add_sourceforgeindexer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitbucketIndexer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_limit_timeout",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        verbose_name="rate limit timeout",
                    ),
                ),
                (
                    "min_forks",
                    models.PositiveIntegerField(
                        default=1, verbose_name="min forks"
                    ),
                ),
                (
                    "current_date",
                    models.DateTimeField(
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        help_text="The creation date of repository from which to start searching. Please note that Bitbucket API paginates repos by creation date, so the dates are used to iterate over repositories.",
                        verbose_name="current date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitbucket Indexer",
                "verbose_name_plural": "Bitbucket Indexer",
            },
        ),
    ]
