# Generated by Django 4.0.5 on 2022-06-03 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexers', '0005_add_bitbucketindexer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabIndexer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_limit_timeout', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='rate limit timeout')),
                ('min_forks', models.PositiveIntegerField(default=1, verbose_name='min forks')),
                ('min_stars', models.PositiveIntegerField(default=0, verbose_name='min stars')),
                ('last_project_id', models.PositiveIntegerField(default=0, help_text='The last processed project id.', verbose_name='last project id')),
            ],
            options={
                'verbose_name': 'GitLab Indexer',
                'verbose_name_plural': 'GitLab Indexer',
            },
        ),
    ]
