# Generated by Django 4.0.3 on 2022-03-31 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the repository",
                        max_length=255,
                        verbose_name="Repository name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the repository",
                        max_length=2048,
                        null=True,
                        verbose_name="Repository description",
                    ),
                ),
                (
                    "analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the repository has been analyzed.",
                        verbose_name="Analyzed",
                    ),
                ),
                (
                    "git_url",
                    models.URLField(
                        help_text="The url used to clone the repository",
                        verbose_name="git url",
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        help_text="The url used to crawl or visit the repository.",
                        verbose_name="repo url",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="The commit hash actual at the time of crawling.",
                        max_length=40,
                        verbose_name="commit hash",
                    ),
                ),
                (
                    "discovered_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the repository was discovered. It is set automatically on creation.",
                        verbose_name="discovered time",
                    ),
                ),
                (
                    "fetch_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when the repository was downloaded.",
                        null=True,
                        verbose_name="fetch time",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
            },
        ),
        migrations.CreateModel(
            name="RepositoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the file has been analyzed or not.",
                        verbose_name="Analyzed",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("C", "C"),
                            ("C++", "Cpp"),
                            ("C#", "C Sharp"),
                            ("CSS", "Css"),
                            ("Java", "Java"),
                            ("JS", "Js"),
                            ("PHP", "Php"),
                            ("Ruby", "Ruby"),
                        ],
                        help_text="Programming language present in the repository.",
                        max_length=20,
                        verbose_name="programming language",
                    ),
                ),
                (
                    "repo_relative_file_path",
                    models.FilePathField(
                        blank=True,
                        help_text="File path, relative to the repository root.",
                        null=True,
                        path="/usr/fregepoc-tmp/",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        help_text="The metrics of the file.",
                        null=True,
                        verbose_name="metrics",
                    ),
                ),
                (
                    "analyzed_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the file was analyzed.",
                        verbose_name="analyzed time",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="The repository that this file belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="repositories.repository",
                    ),
                ),
            ],
        ),
    ]
