# Generated by Django 4.0.3 on 2022-03-17 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "git_url",
                    models.URLField(
                        help_text="The url used to clone the repository",
                        verbose_name="git url",
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        help_text="The url used to crawl or visit the repository.",
                        verbose_name="repo url",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="The commit hash actual at the time of crawling.",
                        max_length=40,
                        verbose_name="commit hash",
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the repository has got discovered. It is set automatically on creation.",
                        verbose_name="crawl time",
                    ),
                ),
                (
                    "download_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when the repository has got downloaded.",
                        null=True,
                        verbose_name="download time",
                    ),
                ),
            ],
        ),
    ]
