# Generated by Django 4.0.3 on 2022-03-21 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "git_url",
                    models.URLField(
                        help_text="The url used to clone the repository",
                        verbose_name="git url",
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        help_text="The url used to crawl or visit the repository.",
                        verbose_name="repo url",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="The commit hash actual at the time of crawling.",
                        max_length=40,
                        verbose_name="commit hash",
                    ),
                ),
                (
                    "crawl_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the repository was discovered. It is set automatically on creation.",
                        verbose_name="crawl time",
                    ),
                ),
                (
                    "download_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when the repository was downloaded.",
                        null=True,
                        verbose_name="download time",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("C", "C"),
                            ("C++", "Cpp"),
                            ("C#", "C Sharp"),
                            ("CSS", "Css"),
                            ("Java", "Java"),
                            ("JS", "Js"),
                            ("PHP", "Php"),
                            ("Ruby", "Ruby"),
                        ],
                        help_text="Programming language present in the repository.",
                        max_length=20,
                        verbose_name="programming language",
                    ),
                ),
                (
                    "analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the repository has been analyzed with regard to this language.",
                        verbose_name="analyzed",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="The related repository.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_languages",
                        to="repositories.repository",
                        verbose_name="repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryLanguageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FilePathField(path="/tmp/")),
                (
                    "repository_language",
                    models.ForeignKey(
                        help_text="The source code.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="repositories.repositorylanguage",
                        verbose_name="source code files",
                    ),
                ),
            ],
        ),
    ]
