# Generated by Django 4.0.3 on 2022-03-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="name",
            field=models.CharField(
                default="noname",
                help_text="The name of the repository",
                max_length=255,
                verbose_name="Repository name",
            ),
            preserve_default=False,
        ),
    ]
