# Generated by Django 4.0.3 on 2022-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0002_repository_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="The description of the repository",
                max_length=2048,
                null=True,
                verbose_name="Repository description",
            ),
        ),
    ]
