# Generated by Django 4.0.8 on 2022-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_alter_repositoryfile_language_rust'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='absolute_file_path',
            field=models.CharField(blank=True, help_text='Absolute file path', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'Cpp'), ('C#', 'C Sharp'), ('CSS', 'Css'), ('Java', 'Java'), ('JS', 'Js'), ('PHP', 'Php'), ('Ruby', 'Ruby'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Golang', 'Golang')], help_text='Programming language present in the repository.', max_length=20, verbose_name='programming language'),
        ),
    ]
