# Generated by Django 4.0.10 on 2023-04-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_alter_repositoryfile_language_rust'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='average_cyclomatic_complexity',
            field=models.FloatField(blank=True, help_text='average cyclomatic complexity of file', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='average_function_name_length',
            field=models.FloatField(blank=True, help_text='average function name length in file', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='average_lines_of_code',
            field=models.FloatField(blank=True, help_text='average lines of code', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='average_parameter_count',
            field=models.FloatField(blank=True, help_text='average parameter count', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='average_token_count',
            field=models.FloatField(blank=True, help_text='average token count', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='function_count',
            field=models.FloatField(blank=True, help_text='number of functions in file', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='lines_of_code',
            field=models.FloatField(blank=True, help_text='Total lines of code in file', null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='token_count',
            field=models.FloatField(blank=True, help_text='token count in file', null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'Cpp'), ('C#', 'C Sharp'), ('CSS', 'Css'), ('Java', 'Java'), ('JS', 'Js'), ('PHP', 'Php'), ('Ruby', 'Ruby'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Golang', 'Golang'), ('Scala', 'Scala'), ('Swift', 'Swift'), ('TypeScript', 'Typescript')], help_text='Programming language present in the repository.', max_length=20, verbose_name='programming language'),
        ),
    ]
