# Generated by Django 4.0.10 on 2023-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_repositorycommitmessagesquality_commitmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='analyzed_time',
            field=models.DateTimeField(blank=True, help_text='The time when the repository was analyzed.', null=True, verbose_name='analyzed time'),
        ),
    ]
