# Generated by Django 5.1.7 on 2025-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_repository_analyzed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='analysis_failed',
            field=models.BooleanField(default=False),
        ),
    ]
