# Generated by Django 5.1.7 on 2025-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0010_repositoryfile_analysis_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='analysis_failed',
            field=models.BooleanField(default=False, help_text='Whether the file analysis failed.', verbose_name='Analysis failed'),
        ),
    ]
