# Generated by Django 5.1.7 on 2025-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0011_alter_repositoryfile_analysis_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(help_text='Programming language present in the repository.', max_length=20, verbose_name='programming language'),
        ),
    ]
