# Generated by Django 5.1.7 on 2025-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0012_alter_repositoryfile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'Cpp'), ('C#', 'C Sharp'), ('CSS', 'Css'), ('Java', 'Java'), ('JS', 'Js'), ('PHP', 'Php'), ('Ruby', 'Ruby'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Golang', 'Golang'), ('Scala', 'Scala'), ('Swift', 'Swift'), ('TypeScript', 'Typescript')], help_text='Programming language present in the repository.', max_length=20, verbose_name='programming language'),
        ),
    ]
