# Generated by Django 5.1.7 on 2026-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0014_alter_repository_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='analysis_failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
