# Generated by Django 4.0.3 on 2022-04-01 00:02

import datetime

from django.db import migrations, models

import fregepoc.indexers.base
import fregepoc.indexers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubIndexer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_forks",
                    models.PositiveIntegerField(
                        default=100, verbose_name="min forks"
                    ),
                ),
                (
                    "min_stars",
                    models.PositiveIntegerField(
                        default=100, verbose_name="min stars"
                    ),
                ),
                (
                    "current_page",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The last visited page via GitHub API.",
                        verbose_name="min stars",
                    ),
                ),
                (
                    "rate_limit_timeout",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        verbose_name="rate limit timeout",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, fregepoc.indexers.base.BaseIndexer),
        ),
    ]
