# Generated by Django 4.0.3 on 2022-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubindexer",
            name="current_page",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The last visited page via GitHub API.",
                verbose_name="current page",
            ),
        ),
    ]
