{
 "title": "All Collected Metrics",
 "time": { "from": "now-1y/y", "to": "now" },
 "panels": [
  {
   "title": "Analyzed Repositories Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT analyzed_time AS time, SUM(COUNT(*)) OVER (ORDER BY analyzed_time) AS analyzed_repositories FROM repositories_repository WHERE analyzed = true GROUP BY analyzed_time ORDER BY analyzed_time",
     "legendFormat": "Cumulative already Analyzed Count"
    },
    {
     "rawSql": "SELECT discovered_time AS time, SUM(COUNT(*)) OVER (ORDER BY discovered_time) AS all_discovered_repositories FROM repositories_repository GROUP BY discovered_time ORDER BY discovered_time",
     "legendFormat": "Cumulative All discovered repository count"
    },
    {
     "rawSql": "SELECT fetch_time AS time, SUM(COUNT(*)) OVER (ORDER BY fetch_time) AS fetched_repositories FROM repositories_repository GROUP BY fetch_time ORDER BY fetch_time",
     "legendFormat": "Cumulative All fetched repository count"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM repositories_repositoryfile\nORDER BY id"
    }
   ]
  },
  {
   "title": "Repository Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM repositories_repository\n"
    }
   ]
  },
  {
   "title": "Commit Messages Quality for Repositories",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM repositories_repositorycommitmessagesquality\n"
    }
   ]
  },
  {
   "title": "Commit Messages metrics (last 1000 records)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM repositories_commitmessage\nORDER BY id DESC\nLIMIT 1000"
    }
   ]
  }
 ]
}