from frege.analyzers.core.c import *
from frege.analyzers.core.cpp import *
from frege.analyzers.core.csharp import *
from frege.analyzers.core.golang import *
from frege.analyzers.core.java import *
from frege.analyzers.core.javascript import *
from frege.analyzers.core.kotlin import *
from frege.analyzers.core.php import *
from frege.analyzers.core.python import *
from frege.analyzers.core.ruby import *
from frege.analyzers.core.rust import *
from frege.analyzers.core.scala import *
from frege.analyzers.core.swift import *
from frege.analyzers.core.typescript import *
