name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p ~/frege-app
            
            rm -rf ~/frege-app/repo
            mkdir -p ~/frege-app/repo
            
            cat > ~/frege-app/.env << EOL
            GITLAB_TOKEN=\${{ secrets.GITLAB_TOKEN }}
            # Add any other necessary environment variables
            EOL

      - name: Copy repository to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./"
          target: "~/frege-app/repo"
          rm: false
          strip_components: 0

      - name: Build and run on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/frege-app/repo
            
            cp .env.template .env
            
            docker compose --profile prod down
            docker compose --profile prod build
            docker compose --profile prod up -d