name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env variables
        run: cp .env.template .env
      - name: Build
        run: docker compose --profile dev build
      - name: Run
        run: docker compose --profile dev up -d
      - name: Check Docker Compose Logs
        run: docker compose logs
      - name: Ensure Containers are Running
        run: docker compose ps
      - name: Run tests
        run: docker compose exec -T frege-backend-dev pytest
      - name: Run consumers test
        run: |
          iteration=1
          while true; do
            echo "Running test iteration $iteration"
            docker compose exec -T frege-backend-dev pytest frege/repositories/tests/test_consumers.py --showlocals
            iteration=$((iteration + 1))
          done